(define-simple-class MyApp (processing.core.PApplet) 

	((setup) 
		(size screenWidth screenHeight codeanticode.glgraphics.GLConstants:GLGRAPHICS) 
		(background 255)
		(ellipseMode CENTER)
		(smooth)
	)
	((draw)
		(yellowline)
		(cyanline)
		(magentaline)
		(blackline)
	)
	((yellowline)
		(pushMatrix)
		(translate (random width) 0)
		(strokeWeight (random 20))
		(stroke (- 255 (random 20)) (- 255 (random 20)) (- 255 (random 255)))
		(noFill)
		(line 0 0 0 height)
		(popMatrix)
	)
	((cyanline)
		(pushMatrix)
		(translate (random width) 0)
		(strokeWeight (random 20))
		(stroke (- 255 (random 255)) (- 255 (random 20)) (- 255 (random 20)))
		(noFill)
		(line 0 0 0 height)
		(popMatrix)
	)
	((magentaline)
		(pushMatrix)
		(translate (random width) 0)
		(strokeWeight (random 20))
		(stroke (- 255 (random 20)) (- 255 (random 255)) (- 255 (random 20)))
		(noFill)
		(line 0 0 0 height)
		(popMatrix)
	)
	((blackline)
		(pushMatrix)
		(translate (random width) 0)
		(strokeWeight 200)
		(stroke (- 255 (random 255)))
		(noFill)
		(line 0 0 0 height)
		(popMatrix)
	)
	((keyPressed)
		(background 255)
	)

)

(define-simple-class NewClass ()
	((draw)
		(background 0)
	)
)

;(processing.core.PApplet:main (make String[] "--present" "MyApp"))

(define p (MyApp))
(MyApp:runSketch (make String[] "--present" "MyApp")  p)
(define g (*:.g p))

;(define nn (NewClass))
;(p:registerDraw nn)



